
name: Build Texture Atlas

on:
  push:
    paths:
      - 'Images/**'
      - '.github/workflows/atlas.yml'
  workflow_dispatch:

jobs:
  pack-atlas:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Download and run Unciv for atlas packing
      run: |
        wget -q -O Unciv.jar \
          $(curl -sL https://api.github.com/repos/yairm210/unciv/releases/latest \
            | grep -o "http.*Unciv.jar")
        java -jar Unciv.jar mod-ci

    - name: Commit and create PR if atlas changed
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: "📦 Rebuild texture atlas"
        title: "Rebuild texture atlas"
        body: |
          Привіт!  
          Я автоматично перегенерував `game.png` та `game.atlas` в результаті змін у папці `Images/`.
        paths: |
          Images/game.png
          Images/game.atlas
